=== sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/config/schema/template-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    Import XML namespace (used by xincludes)
    -->
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>

    <xs:include schemaLocation="properties-1.0.xsd"/>
    <xs:include schemaLocation="schema-1.0.xsd"/>

    <xs:element name="template" type="templateType"/>

    <xs:complexType name="templateType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="key" minOccurs="1" maxOccurs="1">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:maxLength value="31"/>
                        <xs:pattern value="[a-z0-9_-]+"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
            <xs:element type="xs:string" name="group" minOccurs="0" maxOccurs="1"/>
            <xs:element type="indexType" name="index" minOccurs="1" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" maxOccurs="unbounded"/>
            <xs:element type="xs:string" name="view" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="controller" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="internal" minOccurs="0" maxOccurs="1"/>
            <xs:element type="cacheLifetimeType" name="cacheLifetime" minOccurs="1" maxOccurs="1"/>
            <xs:element type="areasType" name="areas"/>
            <xs:element type="schemaType" name="schema" minOccurs="1" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>

            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                        <xs:element type="xs:integer" name="priority" minOccurs="0"/>
                    </xs:choice>
                    <xs:attributeGroup ref="defaultAttributes"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="cacheLifetimeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" default="seconds">
                    <xs:simpleType>
                        <xs:union memberTypes="cacheLifetimeTypeEnum cacheLifetimeTypeAnyString"/>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="cacheLifetimeTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="seconds"/>
            <xs:enumeration value="expression"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cacheLifetimeTypeAnyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="indexType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== sulu/sulu/packages/page/tests/Application/config/templates/pages/publish-required.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>publish-required</key>

    <view>views/pages/page</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>2400</cacheLifetime>

    <tag name="sulu_content.request_workflow" workflow="publish_required"/>

    <meta>
        <title lang="en">Description required to publish</title>
        <title lang="de">Beschreibung zum Veröffentlichen erforderlich</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <tag name="sulu.rlp.part"/>
        </property>

        <property name="url" type="route">
            <meta>
                <title lang="en">Resourcelocator</title>
                <title lang="de">Adresse</title>
            </meta>

            <tag name="sulu.rlp"/>
        </property>

        <property name="description" type="text_line">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>

            <tag name="sulu_content.publish_required_pre_validator"/>
        </property>
    </properties>
</template>

=== sulu/sulu/packages/content/tests/Application/config/templates/examples/example-review-workflow.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>example-review-workflow</key>

    <view>@ExampleTest/examples/default</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>604800</cacheLifetime>

    <tag name="sulu_content.request_workflow" workflow="review"/>

    <meta>
        <title lang="en">Example Review Workflow</title>
        <title lang="de">Example Review Workflow</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
            </meta>
            <tag name="sulu.rlp.part"/>
            <tag name="sulu.search.field" role="title"/>
        </property>

        <property name="url" type="route">
            <meta>
                <title lang="en">URL</title>
            </meta>
            <tag name="sulu.rlp"/>
        </property>
    </properties>
</template>

=== sulu/sulu/packages/content/tests/Application/config/templates/examples/default.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <view>@ExampleTest/examples/default</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>604800</cacheLifetime>

    <meta>
        <title lang="en">Example</title>
        <title lang="de">Example</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <params>
                <param name="headline" value="true"/>
            </params>

            <tag name="sulu.rlp.part"/>
            <tag name="sulu.search.field" role="title"/>
        </property>

        <property name="url" type="route">
            <meta>
                <title lang="en">Resourcelocator</title>
                <title lang="de">Adresse</title>
            </meta>

            <tag name="sulu.rlp"/>
            <tag name="sulu.search.field" role="url"/>
        </property>

        <property name="description" type="text_area">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>

            <tag name="sulu.search.field" role="description"/>
        </property>

        <property name="image" type="single_media_selection">
            <meta>
                <title lang="en">Image</title>
                <title lang="de">Bild</title>
            </meta>

            <tag name="sulu.search.field" role="image"/>
        </property>

        <property name="article" type="text_editor">
            <meta>
                <title lang="en">Article</title>
                <title lang="de">Artikel</title>
            </meta>

            <tag name="sulu.search.field" type="string"/>
        </property>

        <block name="blocks" default-type="text">
            <meta>
                <title lang="en">Content</title>
                <title lang="de">Inhalt</title>
            </meta>

            <types>
                <type name="heading">
                    <meta>
                        <title lang="en">Heading</title>
                        <title lang="de">Überschrift</title>
                    </meta>

                    <properties>
                        <property name="heading" type="text_line">
                            <meta>
                                <title lang="en">Heading</title>
                                <title lang="de">Überschrift</title>
                            </meta>

                            <tag name="sulu.search.field" type="string"/>
                        </property>
                    </properties>
                </type>

                <type name="text">
                    <meta>
                        <title lang="en">Text</title>
                        <title lang="de">Text</title>
                    </meta>

                    <properties>
                        <property name="text" type="text_editor">
                            <meta>
                                <title lang="en">Text</title>
                                <title lang="de">Text</title>
                            </meta>

                            <tag name="sulu.search.field" type="string"/>
                        </property>
                    </properties>
                </type>

                <type name="media">
                    <meta>
                        <title lang="en">Media</title>
                        <title lang="de">Medien</title>
                    </meta>

                    <properties>
                        <property name="media" type="media_selection">
                            <meta>
                                <title lang="en">Media</title>
                                <title lang="de">Medien</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>

        <property name="examples" type="example_selection">
            <meta>
                <title lang="en">Examples</title>
                <title lang="de">Beispiele</title>
            </meta>
        </property>
    </properties>
</template>

=== sulu/sulu/src/Sulu/Bundle/AdminBundle/Resources/js/components/BlockCollection/tests/fixtures/menu.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xmlns:xi="http://www.w3.org/2001/XInclude"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>menu</key>
    <areas>
        <area key="menu">
            <meta>
                <title lang="en">Menu</title>
                <title lang="pl">Menu</title>
                <title lang="hy">Մենյու</title>
                <title lang="hu">Menü</title>
            </meta>
        </area>
    </areas>
    <meta>
        <title lang="en">Menu</title>
        <title lang="pl">Górna nawigacja</title>
        <title lang="hy">Մենյու</title>
        <title lang="hu">Felső navigáció</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="pl">Nazwa</title>
                <title lang="hy">Անվանում</title>
                <title lang="hu">Név</title>
            </meta>

            <tag name="sulu.node.name"/>
        </property>
        <section name="logo_and_links">
            <meta>
                <title lang="en">Logo and links</title>
                <title lang="pl">Logo i linki</title>
                <title lang="hy">Լոգո և հղումներ</title>
                <title lang="hu">Logó és linkek</title>
            </meta>
            <properties>
                <property name="logo" type="single_media_selection">
                    <meta>
                        <title lang="pl">Logo</title>
                        <title lang="en">Logo</title>
                        <title lang="hy">Լոգո</title>
                        <title lang="hu">Logó</title>
                    </meta>
                    <params>
                        <param name="types" value="image"/>
                    </params>
                </property>
                <block name="pages" maxOccurs="6">
                    <meta>
                        <title lang="pl">Strony</title>
                        <title lang="en">Pages</title>
                        <title lang="hy">Էջեր</title>
                        <title lang="hu">Oldalak</title>
                    </meta>
                    <types>
                        <type name="page">
                            <properties>
                                <xi:include
                                        href="../fragments/partials/button.xml"
                                        xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)
                                    xpointer(/sulu:properties/sulu:property)"/>
                                <block name="subpages">
                                    <meta>
                                        <title lang="en">Subpages</title>
                                        <title lang="pl">Podstrony</title>
                                        <title lang="hy">Ենթէջեր</title>
                                        <title lang="hu">Aloldalak</title>
                                    </meta>

                                    <types>
                                        <type name="subpage">
                                            <meta>
                                                <title lang="en">Subpage</title>
                                                <title lang="pl">Podstrona</title>
                                                <title lang="hy">Ենթէջ</title>
                                                <title lang="hu">Aloldal</title>
                                            </meta>

                                            <properties>
                                                <xi:include
                                                        href="../fragments/partials/button.xml"
                                                        xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)
                                                    xpointer(/sulu:properties/sulu:property)"/>

												<block name="subpages2">
													<meta>
														<title lang="en">Subpages 2</title>
														<title lang="pl">Podstrony 2</title>
                                                        <title lang="hy">Ենթէջեր 2</title>
                                                        <title lang="hu">Aloldalak 2</title>
													</meta>

													<types>
														<type name="subpage2">
															<meta>
																<title lang="en">Subpage 2</title>
																<title lang="pl">Podstrona 2</title>
                                                                <title lang="hy">Ենթէջ 2</title>
                                                                <title lang="hu">Aloldal 2</title>
															</meta>

															<properties>
																<xi:include
																	href="../fragments/partials/button.xml"
																	xpointer="xmlns(sulu=http://schemas.sulu.io/template/template)
                                                    xpointer(/sulu:properties/sulu:property)"/>
															</properties>
														</type>
													</types>
												</block>
                                            </properties>
                                        </type>
                                    </types>
                                </block>
                            </properties>
                        </type>
                    </types>
                </block>
            </properties>
        </section>
    </properties>
</template>
