=== sulu/sulu/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    Import XML namespace (used by xincludes)
    -->
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>

    <!--
    Attribute group for attributes that are allowed for all elements
    -->
    <xs:attributeGroup name="defaultAttributes">
        <xs:anyAttribute namespace='http://www.w3.org/XML/1998/namespace'/>
    </xs:attributeGroup>

    <xs:element name="template" type="templateType"/>
    <xs:element name="properties" type="rootPropertiesType"/>

    <xs:complexType name="templateType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="xs:string" name="key" minOccurs="1" maxOccurs="1"/>
            <xs:element type="indexType" name="index" minOccurs="1" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" maxOccurs="unbounded"/>
            <xs:element type="xs:string" name="view" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="controller" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="internal" minOccurs="0" maxOccurs="1"/>
            <xs:element type="cacheLifetimeType" name="cacheLifetime" minOccurs="1" maxOccurs="1"/>
            <xs:element type="rootPropertiesType" name="properties" minOccurs="1" maxOccurs="1"/>

            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                    <xs:attributeGroup ref="defaultAttributes"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="metaType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="langType" name="title"/>
            <xs:element type="langType" name="info_text"/>
            <xs:element type="langType" name="placeholder"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="langType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required" type="xs:string"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rootPropertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element type="blockType" name="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="sectionType" name="section" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="sectionType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property"/>
            <xs:element type="blockType" name="block"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertyType" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="paramsType" name="params" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="indexField" minOccurs="0" maxOccurs="1"/>
        </xs:choice>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="blockTypesType" name="types" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="default-type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypesType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="blockTypeType" name="type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypeType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="tagType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:int" name="priority" use="optional"/>
                <xs:anyAttribute namespace="##any" processContents="lax"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="cacheLifetimeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" default="seconds">
                    <xs:simpleType>
                        <xs:union memberTypes="cacheLifetimeTypeEnum cacheLifetimeTypeAnyString"/>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="cacheLifetimeTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="seconds"/>
            <xs:enumeration value="expression"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cacheLifetimeTypeAnyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="meta" type="metaType" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute name="type" type="paramTypeType" default="string"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:simpleType name="paramTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="collection"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="indexType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== sulu/sulu/packages/search/tests/Application/config/templates/pages/overview.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>overview</key>

    <view>::overview</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <tag name="sulu.rlp.part"/>
        </property>

        <property name="tags" type="tag_selection"/>

        <property name="url" type="route" mandatory="true">
            <tag name="sulu.rlp"/>
        </property>

        <property name="article" type="text_line" minOccurs="1" maxOccurs="10"/>

        <block name="block" default-type="type1">
            <types>
                <type name="type1">
                    <properties>
                        <property name="title" type="text_line"/>
                        <property name="article" type="text_line" minOccurs="2"/>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>

=== sulu/sulu/packages/content/tests/Application/config/templates/examples/default-example-selection.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default-example-selection</key>

    <view>@ExampleTest/examples/default</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>604800</cacheLifetime>

    <meta>
        <title lang="en">Example</title>
        <title lang="de">Example</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <params>
                <param name="headline" value="true"/>
            </params>

            <tag name="sulu.rlp.part"/>
            <tag name="sulu.search.field" role="title"/>
        </property>

        <property name="url" type="route">
            <meta>
                <title lang="en">Resourcelocator</title>
                <title lang="de">Adresse</title>
            </meta>

            <tag name="sulu.rlp"/>
            <tag name="sulu.search.field" role="url"/>
        </property>

        <property name="description" type="text_area">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>

            <tag name="sulu.search.field" role="description"/>
        </property>

        <property name="image" type="single_media_selection">
            <meta>
                <title lang="en">Image</title>
                <title lang="de">Bild</title>
            </meta>

            <tag name="sulu.search.field" role="image"/>
        </property>

        <property name="examples" type="example_selection">
            <meta>
                <title lang="en">Page</title>
                <title lang="de">Seite</title>
            </meta>
        </property>

        <property name="examples_with_properties" type="example_selection">
            <meta>
                <title lang="en">Page with properties</title>
                <title lang="de">Seite mit Properties</title>
            </meta>

            <params>
                <param name="properties" type="collection">
                    <param name="id" value="object.id"/>
                    <param name="title" value="title"/>
                    <param name="description" value="description"/>
                    <param name="excerptTitle" value="excerpt.title"/>
                    <param name="excerptDescription" value="excerpt.description"/>
                    <param name="seoTitle" value="seo.title"/>
                    <param name="seoDescription" value="seo.description"/>
                </param>
            </params>
        </property>
    </properties>
</template>

=== sulu/sulu/packages/content/tests/Application/config/templates/examples/default-snippet-selection.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default-snippet-selection</key>

    <meta>
        <title lang="en">Default Snippet Selection</title>
        <title lang="de">Standard Schnipsel Auswahl</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <tag name="sulu.node.name"/>
        </property>

        <property name="url" type="route">
            <meta>
                <title lang="en">URL</title>
                <title lang="de">URL</title>
            </meta>
        </property>

        <property name="snippet" type="single_snippet_selection">
            <meta>
                <title lang="en">Snippet</title>
                <title lang="de">Schnipsel</title>
            </meta>
            <params>
                <param name="properties" type="collection">
                    <param name="description" value="description"/>
                </param>
            </params>
        </property>
    </properties>
</template>

=== sulu/sulu/src/Sulu/Bundle/WebsiteBundle/Tests/Application/config/templates/pages/overview.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd"
>
    <key>overview</key>

    <view>pages/default</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>2400</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="false">
            <tag name="sulu.rlp.part" />
        </property>
        <property name="tags" type="text_line" minOccurs="2" maxOccurs="10"/>
        <property name="url" type="route" mandatory="false">
            <tag name="sulu.rlp" />
        </property>
        <property name="article" type="text_area" mandatory="false"/>
        <property name="blog" type="text_area" mandatory="false"/>
        <property name="external_url" type="url" mandatory="false" />
        <property name="internal_link" type="page_selection" mandatory="false" />
    </properties>
</template>

=== sulu/sulu/tests/Resources/DataFixtures/Page/template_sections.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>template_sections</key>

    <view>page.html.twig</view>
    <controller>SuluPageBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true" colspan="6">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>

                <info_text lang="de">Titel-Info-DE</info_text>
                <info_text lang="en">Title-Info-EN</info_text>

                <placeholder lang="de">Platzhalter-Info-DE</placeholder>
                <placeholder lang="en">Placeholder-Info-EN</placeholder>
            </meta>
            <tag name="sulu.node.title" priority="10"/>
        </property>

        <section name="test" cssClass="test">
            <meta>
                <title lang="de">Test-DE</title>
                <title lang="en">Test-EN</title>

                <info_text lang="de">Info-DE</info_text>
                <info_text lang="en">Info-EN</info_text>
            </meta>
            <properties>
                <property name="url" type="route" mandatory="true" cssClass="test"
                          colspan="6">
                    <tag name="sulu.rlp" priority="1"/>
                </property>
                <property name="article" type="text_area" mandatory="false" colspan="6">
                    <tag name="sulu.node.title" priority="5"/>
                </property>
                <block name="block" default-type="test">
                    <meta>
                        <title lang="de">Block-DE</title>
                        <title lang="en">Block-EN</title>

                        <info_text lang="de">Block-Info-DE</info_text>
                        <info_text lang="en">Block-Info-EN</info_text>
                    </meta>
                    <types>
                        <type name="test">
                            <properties>
                                <property name="name" type="text_line"/>
                            </properties>
                        </type>
                    </types>
                </block>
            </properties>
        </section>

        <property name="pages" type="smart_content_selection" mandatory="false">
            <tag name="sulu.node.title"/>
        </property>

        <property name="images" type="image_selection" minOccurs="0" maxOccurs="2" colspan="6">
            <params>
                <param name="minLinks" value="1"/>
                <param name="maxLinks" value="10"/>
            </params>
        </property>
    </properties>
</template>

=== sulu/sulu/tests/Resources/DataFixtures/Page/template_load_internal.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>template</key>

    <view>page.html.twig</view>
    <controller>SuluPageBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>
    <index name="foo_index" />

    <internal>true</internal>

    <meta>
        <title lang="de">Das ist das Template 1</title>
        <title lang="en">That´s the template 1</title>
    </meta>

    <tag name="some.random.structure.tag" foo="bar" bar="foo"/>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Titel</title>
                <title lang="en">Title</title>

                <info_text lang="de">Titel-Info-DE</info_text>
                <info_text lang="en">Title-Info-EN</info_text>

                <placeholder lang="de">Platzhalter-Info-DE</placeholder>
                <placeholder lang="en">Placeholder-Info-EN</placeholder>
            </meta>

            <indexField />

            <tag name="sulu.node.title" priority="10"/>

            <tag name="some.random.tag" one="1" two="2" three="three" />
        </property>

        <property name="url" type="route" mandatory="true">
            <tag name="sulu.rlp" priority="1"/>
        </property>

        <property name="article" type="text_area" mandatory="false">
            <tag name="sulu.node.title" priority="5"/>
        </property>

        <property name="pages" type="smart_content_selection" mandatory="false">
            <tag name="sulu.node.title"/>
        </property>

        <property name="article_number" type="text_line" multilingual="false"/>

        <property name="images" type="image_selection" minOccurs="0" maxOccurs="2">
            <params>
                <param name="minLinks" value="1"/>
                <param name="maxLinks" value="10"/>
                <param name="displayOptions" type="collection">
                    <param name="leftTop" value="true"/>
                    <param name="top" value="false"/>
                    <param name="rightTop" value="true"/>
                    <param name="left" value="false"/>
                    <param name="middle" value="false"/>
                    <param name="right" value="false"/>
                    <param name="leftBottom" value="true"/>
                    <param name="bottom" value="false"/>
                    <param name="rightBottom" value="true"/>
                </param>
            </params>
        </property>
    </properties>
</template>

=== sulu/sulu/packages/content/tests/Application/config/templates/examples/default-example-smart-content-paginated.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>example-smart-paginated</key>

    <view>@ExampleTest/examples/default</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>604800</cacheLifetime>

    <meta>
        <title lang="en">Example Paginated</title>
        <title lang="de">Example Paginiert</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <params>
                <param name="headline" value="true"/>
            </params>

            <tag name="sulu.rlp.part"/>
            <tag name="sulu.search.field" role="title"/>
        </property>

        <property name="url" type="route">
            <meta>
                <title lang="en">Resourcelocator</title>
                <title lang="de">Adresse</title>
            </meta>

            <tag name="sulu.rlp"/>
            <tag name="sulu.search.field" role="url"/>
        </property>

        <property name="description" type="text_area">
            <meta>
                <title lang="en">Description</title>
                <title lang="de">Beschreibung</title>
            </meta>

            <tag name="sulu.search.field" role="description"/>
        </property>

        <property name="examples" type="smart_content">
            <meta>
                <title lang="en">Examples Smart Content</title>
                <title lang="de">Examples Smart Content</title>
            </meta>

            <params>
                <param name="provider" value="examples"/>
                <param name="max_per_page" value="1"/>
            </params>
        </property>

        <property name="examples_with_properties" type="smart_content">
            <meta>
                <title lang="en">Examples Smart Content with properties</title>
                <title lang="de">Examples Smart Content mit Properties</title>
            </meta>

            <params>
                <param name="provider" value="examples"/>
                <param name="max_per_page" value="1"/>
                <param name="properties" type="collection">
                    <param name="id" value="object.resource.id"/>
                    <param name="title" value="title"/>
                    <param name="description" value="description"/>
                    <param name="excerptTitle" value="excerpt.title"/>
                    <param name="excerptDescription" value="excerpt.description"/>
                    <param name="seoTitle" value="seo.title"/>
                    <param name="seoDescription" value="seo.description"/>
                </param>
            </params>
        </property>
    </properties>
</template>

=== sulu/sulu/tests/Resources/DataFixtures/Page/template_block_type_without_meta.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>template_block_types</key>

    <view>pages/template_block_type_without_meta</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>4800</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <tag name="sulu.node.title" priority="10"/>
        </property>
        <property name="url" type="route" mandatory="true">
            <tag name="sulu.rlp" priority="1"/>
        </property>
        <block name="block1" default-type="default" minOccurs="2" maxOccurs="10" mandatory="true">
            <meta>
                <title lang="de">Block1 DE</title>
                <title lang="en">Block1 EN</title>
                <info_text lang="de">Info Block1 DE</info_text>
                <info_text lang="en">Info Block1 EN</info_text>
                <placeholder lang="de">Placeholder Block1 DE</placeholder>
                <placeholder lang="en">Placeholder Block1 EN</placeholder>
            </meta>
            <tag name="sulu.node.block" priority="20"/>
            <tag name="sulu.test.block" priority="1"/>
            <types>
                <type name="default">
                    <properties>
                        <property name="title" type="text_line" mandatory="true"/>
                        <property name="article" type="text_area" mandatory="true" minOccurs="2"/>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>
