=== sulu/sulu/src/Sulu/Component/Content/Metadata/Loader/schema/template-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           targetNamespace="http://schemas.sulu.io/template/template"
           xmlns="http://schemas.sulu.io/template/template"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--
    Import XML namespace (used by xincludes)
    -->
    <xs:import namespace='http://www.w3.org/XML/1998/namespace' schemaLocation='xml.xsd'/>

    <!--
    Attribute group for attributes that are allowed for all elements
    -->
    <xs:attributeGroup name="defaultAttributes">
        <xs:anyAttribute namespace='http://www.w3.org/XML/1998/namespace'/>
    </xs:attributeGroup>

    <xs:element name="template" type="templateType"/>
    <xs:element name="properties" type="rootPropertiesType"/>

    <xs:complexType name="templateType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="xs:string" name="key" minOccurs="1" maxOccurs="1"/>
            <xs:element type="indexType" name="index" minOccurs="1" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" maxOccurs="unbounded"/>
            <xs:element type="xs:string" name="view" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="controller" minOccurs="1" maxOccurs="1"/>
            <xs:element type="xs:string" name="internal" minOccurs="0" maxOccurs="1"/>
            <xs:element type="cacheLifetimeType" name="cacheLifetime" minOccurs="1" maxOccurs="1"/>
            <xs:element type="rootPropertiesType" name="properties" minOccurs="1" maxOccurs="1"/>

            <xs:element name="meta">
                <xs:complexType>
                    <xs:choice maxOccurs="unbounded">
                        <xs:element type="langType" name="title"/>
                    </xs:choice>
                    <xs:attributeGroup ref="defaultAttributes"/>
                </xs:complexType>
            </xs:element>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="metaType">
        <xs:choice maxOccurs="unbounded">
            <xs:element type="langType" name="title"/>
            <xs:element type="langType" name="info_text"/>
            <xs:element type="langType" name="placeholder"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="langType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="lang" use="required" type="xs:string"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="rootPropertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property" minOccurs="1" maxOccurs="unbounded"/>
            <xs:element type="blockType" name="block" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="sectionType" name="section" minOccurs="0" maxOccurs="unbounded"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="sectionType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertiesType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element type="propertyType" name="property"/>
            <xs:element type="blockType" name="block"/>
        </xs:choice>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="propertyType" mixed="true">
        <xs:choice minOccurs="0" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="paramsType" name="params" minOccurs="0" maxOccurs="1"/>
            <xs:element type="xs:string" name="indexField" minOccurs="0" maxOccurs="1"/>
        </xs:choice>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockType">
        <xs:sequence minOccurs="1" maxOccurs="unbounded">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="tagType" name="tag" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element type="blockTypesType" name="types" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attribute type="xs:string" name="default-type" use="required"/>
        <xs:attribute type="xs:string" name="mandatory" use="optional"/>
        <xs:attribute type="xs:string" name="multilingual" use="optional"/>
        <xs:attribute type="xs:nonNegativeInteger" name="minOccurs" use="optional"/>
        <xs:attribute type="xs:positiveInteger" name="maxOccurs" use="optional"/>
        <xs:attribute type="xs:string" name="cssClass" use="optional"/>
        <xs:attribute type="xs:integer" name="colspan" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypesType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="blockTypeType" name="type" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="blockTypeType">
        <xs:sequence minOccurs="1" maxOccurs="1">
            <xs:element type="metaType" name="meta" minOccurs="0" maxOccurs="1"/>
            <xs:element type="propertiesType" name="properties" minOccurs="1" maxOccurs="1"/>
        </xs:sequence>

        <xs:attribute type="xs:string" name="name" use="required"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="tagType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attribute type="xs:int" name="priority" use="optional"/>
                <xs:anyAttribute namespace="##any" processContents="lax"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="cacheLifetimeType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="type" default="seconds">
                    <xs:simpleType>
                        <xs:union memberTypes="cacheLifetimeTypeEnum cacheLifetimeTypeAnyString"/>
                    </xs:simpleType>
                </xs:attribute>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="cacheLifetimeTypeEnum">
        <xs:restriction base="xs:string">
            <xs:enumeration value="seconds"/>
            <xs:enumeration value="expression"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="cacheLifetimeTypeAnyString">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9a-zA-Z]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="paramsType">
        <xs:sequence>
            <xs:element type="paramType" name="param" maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:complexType name="paramType">
        <xs:choice maxOccurs="unbounded">
            <xs:element name="param" type="paramType" minOccurs="0" maxOccurs="unbounded"/>
            <xs:element name="meta" type="metaType" minOccurs="0" maxOccurs="1"/>
        </xs:choice>
        <xs:attribute name="type" type="paramTypeType" default="string"/>
        <xs:attribute name="name" type="xs:string" use="required"/>
        <xs:attribute name="value" type="xs:string" use="optional"/>
        <xs:attributeGroup ref="defaultAttributes"/>
    </xs:complexType>

    <xs:simpleType name="paramTypeType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="collection"/>
            <xs:enumeration value="string"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="indexType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute type="xs:string" name="name" use="required"/>
                <xs:attributeGroup ref="defaultAttributes"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
</xs:schema>

=== sulu/sulu/packages/content/tests/Application/config/templates/examples/smart-content-tag-selection.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>smart-content-tag-selection</key>

    <view>@ExampleTest/examples/default</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>
    <cacheLifetime>604800</cacheLifetime>

    <meta>
        <title lang="en">Smart Content with Tag Selection</title>
        <title lang="de">Smart Content mit Tag Selection</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
            </meta>

            <tag name="sulu.rlp.part"/>
        </property>

        <property name="url" type="route">
            <meta>
                <title lang="en">Resourcelocator</title>
            </meta>

            <tag name="sulu.rlp"/>
        </property>

        <property name="examples" type="smart_content">
            <meta>
                <title lang="en">Examples</title>
            </meta>

            <params>
                <param name="provider" value="examples"/>
            </params>
        </property>

        <property name="featured_tags" type="tag_selection">
            <meta>
                <title lang="en">Featured Tags</title>
            </meta>
        </property>
    </properties>
</template>

=== sulu/sulu/packages/redirect/tests/Application/config/templates/pages/default.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>default</key>

    <view>::default</view>
    <controller>SuluWebsiteBundle:Default:index</controller>
    <cacheLifetime>2400</cacheLifetime>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <tag name="sulu.rlp.part"/>
        </property>

        <property name="tags" type="tag_selection"/>

        <property name="url" type="route" mandatory="true">
            <tag name="sulu.rlp"/>
        </property>

        <property name="snippet" type="text_area" mandatory="false" />
    </properties>
</template>

=== sulu/sulu/src/Sulu/Bundle/AdminBundle/Tests/Application/config/templates/pages/default.xml
<?xml version="1.0" ?>

<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd"
          >

    <key>default</key>

    <view>ClientWebsiteBundle:templates:animals</view>
    <controller>Sulu\Bundle\WebsiteBundle\Controller\DefaultController::indexAction</controller>
    <cacheLifetime>2400</cacheLifetime>

    <meta>
        <title lang="de">Tiers</title>
        <title lang="en">Animals</title>
    </meta>

    <tag name="test" value="test-value"/>
    <tag name="test2" test="test-value2"/>
    <tag name="test3" value="test-value"/>

    <schema>
        <anyOf>
            <schema>
                <properties>
                    <property name="blog" mandatory="true"/>
                </properties>
            </schema>
            <schema>
                <properties>
                    <property name="localized_blog" mandatory="true"/>
                </properties>
            </schema>
        </anyOf>
    </schema>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="de">Tier</title>
                <title lang="en">Animals</title>
            </meta>

            <tag name="sulu.rlp.part" priority="100"/>
        </property>

        <property name="url" type="resource_locator" mandatory="true">
            <meta>
                <title lang="de">Adresse</title>
                <title lang="en">Resourcelocator</title>
            </meta>

            <tag name="sulu.rlp"/>
        </property>

        <!-- TODO readd ? https://github.com/sulu/sulu/pull/7794
        <property name="animals" type="snippet_selection">
            <params>
                <param name="snippetType" value="animal" />
            </params>

            <meta>
                <title lang="de">Tiers</title>
                <title lang="en">Animals</title>
            </meta>
        </property>
        -->

        <property name="blog" type="text_area" multilingual="false" mandatory="false"/>

        <property name="localized_blog" type="text_area" mandatory="false"/>

        <section name="content">
            <properties>
                <block name="blocks" default-type="text_block" minOccurs="0">
                    <types>
                        <type ref="text_block"/>
                        <type ref="text_block2"/>
                        <type name="editor">
                            <meta>
                                <title lang="en">Editor</title>
                                <title lang="de">Editor</title>
                            </meta>
                            <properties>
                                <property name="text_editor" type="text_editor">
                                    <meta>
                                        <title lang="en">Text Editor</title>
                                        <title lang="de">Texteditor</title>
                                    </meta>
                                </property>
                            </properties>
                        </type>
                        <type name="block">
                            <properties>
                                <property name="title" type="text_line"/>
                                <block name="blocks" default-type="text_block2" minOccurs="0">
                                    <types>
                                        <type ref="text_block2"/>
                                        <type ref="text_block3"/>
                                    </types>
                                </block>
                            </properties>
                        </type>
                    </types>
                </block>
            </properties>
        </section>
    </properties>
</template>

=== sulu/sulu/packages/content/tests/Application/config/templates/examples/blocks-with-custom-settings.xml
<?xml version="1.0" ?>
<template xmlns="http://schemas.sulu.io/template/template"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://schemas.sulu.io/template/template http://schemas.sulu.io/template/template-1.0.xsd">

    <key>blocks-with-custom-settings</key>

    <view>@ExampleTest/examples/default</view>
    <controller>Sulu\Content\UserInterface\Controller\Website\ContentController::indexAction</controller>

    <meta>
        <title lang="en">Custom Settings Template</title>
        <title lang="de">Template mit benutzerdefinierten Einstellungen</title>
    </meta>

    <properties>
        <property name="title" type="text_line" mandatory="true">
            <meta>
                <title lang="en">Title</title>
                <title lang="de">Titel</title>
            </meta>

            <tag name="sulu.search.field" role="title"/>
        </property>

        <property name="url" type="route" mandatory="true">
            <meta>
                <title lang="en">Resourcelocator</title>
                <title lang="de">Adresse</title>
            </meta>

            <tag name="sulu.rlp"/>
        </property>

        <block name="blocks_with_custom_settings_form_key" default-type="editor" minOccurs="0">
            <meta>
                <title lang="en">Content with Custom Settings</title>
                <title lang="de">Inhalte mit benutzerdefinierten Einstellungen</title>
            </meta>

            <params>
                <param name="settings_form_key" value="custom_block_settings" />
            </params>

            <types>
                <type name="editor">
                    <meta>
                        <title lang="en">Editor</title>
                        <title lang="de">Editor</title>
                    </meta>
                    <properties>
                        <property name="text_editor" type="text_editor">
                            <meta>
                                <title lang="en">Text Editor</title>
                                <title lang="de">Texteditor</title>
                            </meta>
                        </property>
                    </properties>
                </type>
            </types>
        </block>
    </properties>
</template>
